### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by pandaymx** [vuepress-theme-hope/vuepress-theme-hope#3536]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Error: Cannot find module 'call-bind'
Require stack:
- C:\Users\panda\AppData\Local\Yarn\Data\global\node_modules\@ljharb\through\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\panda\AppData\Local\Yarn\Data\global\node_modules\@ljharb\through\index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\panda\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\@ljharb\\through\\index.js'
  ]
}

Node.js v18.17.1

```[tasklist]
### Tasks
```

**Comment by Mister-Hope** [comment]
It seems you are running cli helper with yarn, yarn v1 is no longer supported, use pnpm/npm or use yarn@berry.

**Comment by Mister-Hope** [comment]
Closing as the issue probably related to your env, further questions are still welcomed in this thread to help you solve your problems.

**Comment by CoderSerio** [comment]
> It seems you are running cli helper with yarn, yarn v1 is no longer supported, use pnpm/npm or use yarn@berry.

same case with using npm v8.19.3(node v16.19.0)

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/79406469/0c893132-fe68-4fc6-8cb9-f1fbc1085695)

**Comment by Mister-Hope** [comment]
It seems to be an upstream issue  or issue with rollup4,  I will check it up later when I have time

**Comment by ljharb** [comment]
It should be fixed now; I just published v2.3.11 of `@ljharb/through`.

**Comment by Mister-Hope** [comment]
Closed, related issue https://github.com/ljharb/through/issues/1 has been solved.
