### ISSUE TITLE
[Roadmap]: V2 plan with VuePress2

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#402]
## Details

V2 will come together with _VuePress@v2_, with the power of _vite@v2_ _webpack@v5_ and _vue@v3_.

V2 will be a totally rewrite including:

- All the components will be rewrite with _composition api in vue3_
- All the styles will be mirgate to _sass_

Also we are going to make sure the rewrite one has a better performance!🚀 (no less than 25% increasement)

---

Below is a list of changes.

> Note: All plugin names are in PascalCase and without `vuepress-plugin-` prefix, you should change to `kebab-case` and add the prefix yourself to get the correct plugin name.

## AddThis💌 ![deprecated](https://img.shields.io/badge/-deprecated-yellow)

We are just making this plugin compatable with V2. This plugin will no longer under maintainment.

### Why❔

AdBlockers are blocking addThis link heavily, and in most cases this plugin won't work.

### Solution💡

We will provide a new share plugin in v2.

## Comment2💬

Renamed from `@mr-hope/vuepress-plugin-comment` to `vuepress-plugin-comment2`. ⚠

### Changes

- [x] Drop Valine support! ![removed](https://img.shields.io/badge/-removed-red)

  Valine is lack of maintainence and can leak your privacy. You should use [Waline](https://waline.js.org) instead.

- [x] Option `hint` (default `true`) for handling page info hints. ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Allow I18N Customize ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Muti categories support ![new](https://img.shields.io/badge/-new-brightgreen)

### Note

Vssue is currently being dropped because vssue has not support v2 yet. We will add it back after it supports v2.

## CopyCode2📋

Renamed from `@mr-hope/vuepress-plugin-copy-code` to `vuepress-plugin-copy-code2`. ⚠

### Changes

- [x] Option `delay` (default `500`) for handling the page swtiching transition. ![new](https://img.shields.io/badge/-new-brightgreen)

- [ ] Option `pure` (default `false`) for handling fancy styles. ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Allow I18N Customize ![new](https://img.shields.io/badge/-new-brightgreen)

## Feed2

Renamed from `@mr-hope/vuepress-plugin-feed` to `vuepress-plugin-feed2`. ⚠

### Changes

- [x] Better log output. ![improve](https://img.shields.io/badge/-improved-blue)

- [x] Muti categories support ![new](https://img.shields.io/badge/-new-brightgreen)

### Changes

- [x] Auto inject cdn links for markdown demo ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Option `delay` (default `500`) for handling the page swtiching transition. ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Drop flowchart support ![removed](https://img.shields.io/badge/-removed-red)

  We are adding mermaid support, and mermaid support flowchart.

- [x] Move SlidePage layout from theme to the plugin

  This will allow other theme to provided a similar layout easily.

- [x] Allow I18N Title in details block ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Allow I18N Customize ![new](https://img.shields.io/badge/-new-brightgreen)

## LightGallery ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Build a photo preview plugin using [lightGallary](https://www.lightgalleryjs.com/)

## Pwa2

Renamed from `@mr-hope/vuepress-plugin-pwa` to `vuepress-plugin-pwa2`. ⚠

### Changes

- [x] Allow I18N Customize ![new](https://img.shields.io/badge/-new-brightgreen)

### Changes

- [x] Option `delay` (default `500`) for handling the page swtiching transition. ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Allow I18N Customize ![new](https://img.shields.io/badge/-new-brightgreen)

## ReadingTime2

Renamed from `@mr-hope/vuepress-plugin-reading-time` to `vuepress-plugin-reading-time2`. ⚠

- [x] Allow I18N Customize ![new](https://img.shields.io/badge/-new-brightgreen)

## SassPalette ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] A new palette handling config and palette across theme and plugins using sass

Options:

```ts
export interface PaletteOptions {
  /** identifier for palette */
  id: string;

  /**
   * user config file path, relative to source dir
   *
   * @default ".vuepress/styles/config.scss"
   */
  config?: string;

  /**
   * default config file path, should be absolute path
   *
   * This is the file you should use to provide default values with `!default`
   *
   * @default "vuepress-plugin-sass-palette/styles/default/config.scss"
   */
  defaultConfig?: string;

  /**
   * user palette file path, relative to source dir
   *
   * @default ".vuepress/styles/palette.scss"
   */
  palette?: string;

  /**
   * default palette file path, should be absolute path
   *
   * This is the file you should use to provide default values with `!default`
   *
   * @default "vuepress-plugin-sass-palette/styles/default/palette.scss"
   */

  defaultPalette?: string;

  /**
   * user style file path, relative to source dir
   *
   * @default ".vuepress/styles/palette.scss"
   */
  style?: string;
}
```

## SEO2

Renamed from `@mr-hope/vuepress-plugin-seo` to `vuepress-plugin-seo2`. ⚠

### Changes

- [x] JSON-LD support ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Better log output. ![improve](https://img.shields.io/badge/-improved-blue)

- [x] Muti categories support ![new](https://img.shields.io/badge/-new-brightgreen)

## Share2 ![new](https://img.shields.io/badge/-new-brightgreen)

- [ ] A new share plugin providing page share.

## SimpleBlog ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Build a own blog plugin to support blog with better performance

## Sitemap2

Renamed from `@mr-hope/vuepress-plugin-sitemap` to `vuepress-plugin-sitemap2`. ⚠

### Changes

- [x] Better log output. ![improve](https://img.shields.io/badge/-improved-blue)

- [x] Muti categories support ![new](https://img.shields.io/badge/-new-brightgreen)

## VuepressThemeHope

- [ ] Pure Mode in theme and all plugins #438 ![new](https://img.shields.io/badge/-new-brightgreen)

- [ ] Dim non focused area #168 ![new](https://img.shields.io/badge/-new-brightgreen)

- [ ] Code block theme config #189 ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Muti categories support ![new](https://img.shields.io/badge/-new-brightgreen)

- [x] Drop fullscreen feature, or make it a optional feature (disabled by default). ![removed](https://img.shields.io/badge/-removed-red)

  Most visitors do not use this feature.

- [x] Drop themecolor feature, or make it a optional feature (disabled by default). ![removed](https://img.shields.io/badge/-removed-red)

  Most visitors do not use this feature.

- [x] Allow I18N Customize ![new](https://img.shields.io/badge/-new-brightgreen)

**Comment by Mister-Hope** [comment]
Any ideas and feedbacks are welcome. Please make your comments [here in dicussion](https://github.com/vuepress-theme-hope/vuepress-theme-hope/discussions/601). ❤

**Comment by Mister-Hope** [comment]
Please track https://github.com/orgs/vuepress-theme-hope/projects/1/ to follow the roadmap.
