### ISSUE TITLE
[Bug]https://xxx.github.io/blog/assets/waline-meta-l0sNRNKZ.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by smallfawn** [vuepress-theme-hope/vuepress-theme-hope#4496]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

https://xxx.github.io/blog/assets/waline-meta-l0sNRNKZ.js net::ERR_ABORTED 404 (Not Found)

安装了waline@clinet了也在config.ts里面配置了 comment: {
      provider: "Waline",
      serverURL: "https://waline.xxx.top",
    },
    
但是打包结果出现以上404 并没有生成该文件

**Comment by smallfawn** [comment]
> 您好。请使用 GitHub 存储库或 [vuepress-theme-hope.github.io/v2-new](https://vuepress-theme-hope.github.io/v2-new) 提供[最小复制](https://stackoverflow.com/help/minimal-reproducible-example)。如果标记为 的问题在 3 天内没有任何活动，则将被关闭。`needs reproduction`

存储库为 https://github.com/smallfawn/blog

**Comment by Mister-Hope** [comment]
Sorry for the long delay, the reproduction seems broken, can you provide a new one with latest version?

**Comment by Mister-Hope** [comment]
Sounds like Vite6 still have this issue. I think this should probably be an upstream bug.

**Comment by dream-oyh** [comment]
我也遇到了这个问题，我的博客网址是dream-oyh.pages.dev，请问需要提供最小复现代码吗？

**Comment by Mister-Hope** [comment]
I think this is fixed in vite7? If the issue still exists, welcome to open a new issue
